version: "3.8"
services:
    
    api:
        image: abdulbarri/hngi9-api
        restart: always
        container_name: api_c
        ports:
            - '8000:8000'
    
    frontend:
        image: abdulbarri/hngi9-frontend
        restart: always
        container_name: frontend_c
        ports:
            - '3000:3000'
   
