version: "3.8"
services:
    
    api:
        image: abdulbarri/hngi9-api
        container_name: api_c
        ports:
            - '8000:8000'
    
    frontend:
        image: abdulbarri/hngi9-frontend
        container_name: frontend_c
        ports:
            - '3000:3000'
    
#     nginx:
#         image: nginx:latest
#         ports:
#             - 80:3000
#         depends_on:
#             - api
#             - frontend
