version: "3.8"
services:
    
    api:
        build: ./api
        container_name: api_c
        ports:
            - '8000:8000'
        volumes:
            - ./api:/app
    
    frontend:
        build: ./frontend
        container_name: frontend_c
        ports:
            - '3000:3000'
        volumes: 
            - ./frontend:/app
            - ./app/node_modules
    
#     nginx:
#         image: nginx:latest
#         ports:
#             - 80:3000
#         depends_on:
#             - api
#             - frontend
