version: "3.8"
services:
    
    api:
        build: ./api
        container_name: api_c
        volumes:
            - ./api:/app
    
    frontend:
        build: ./frontend
        container_name: frontend_c
        ports:
            - '3000:3000'
        volumes: 
            - ./frontend:/app
            - ./app/node_modules
    
    nginx:
    image: nginx:latest
        ports:
            - 80:3000
        volumes:
            - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
            - react_build:/var/www/react
        depends_on:
            - api
            - frontend